version: '3'

services:
  # Car Heartbeat Microservice Application
  ping:
    build:
      context: ./fms/
      dockerfile: ping.dockerfile
    links:
      - rabbitmq

  # Database Microservice Application
  dbms:
    build:
      context: ./fms/
      dockerfile: db.dockerfile
    ports:
      - "3000:3000"
    links:
      - rabbitmq

  # Monitoring Microservice Application
  monitoring:
    build:
      context: ./fms/
      dockerfile: monitoring.dockerfile
    links:
      - rabbitmq

  # RabbitMQ Image
  rabbitmq:
    image: "rabbitmq:3.7.4"
    ports:
      - "5673:5672"
      - "15672:15672"

  # Database Image
  mysql:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=fms"
      - "MYSQL_USER=fms"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "3306:3306"

  # MongoDB Image
  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

# Database Volumes
volumes:
  dbdata:
  mongodata:
